---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: studentwebappv2development
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: studentwebappv2
  template:
    metadata:
      name: studentwebappv2pod
      labels:
        app: studentwebappv2
    spec:
      containers:
      - name: studentwebappv2container
        image: thannidocer/studentwebappv2
        ports:
          - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: studentwebappv2svc
spec:
  type: NodePort
  selector:
    app: studentwebappv2
  ports:
    - port: 81
      targetPort: 8081
      nodePort: 30786
---