---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: studentwebappdevelopment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: studentwebapp
  template:
    metadata:
      name: studentwebapppod
      labels:
        app: studentwebapp 
    spec:
      containers:
      - name: studentwebappcontainer
        image: thannidocer/studentwebapp
        ports:
          - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: studentwebappsvc
spec:
  type: NodePort
  selector:
    app: studentwebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785
---